[package]
name = "shopifyw19"
version = "0.1.0"
authors = ["Scetch <lucierbrandon@gmail.com>"]

[dependencies]
actix-web = "0.7.6"
diesel = "1.3.2"
serde = "1.0.78"
serde_derive = "1.0.78"
serde_json = "1.0.27"
